Repository stmtstk/mitre_attack_csv, pull requests merged in 2022-08, with the labels that each got.

#7 Update mitre_attack_csv.py
  mitre_attack_csv.py
Labels: enhancement

#5 Reflected the latest updates
  README.md
Labels: documentation

#11 Updated README.md
  README.md
Labels: documentation

#14 add version option
  mitre_attack_csv.py
Labels: enhancement

#17 Issue #15
  README.md
Labels: duplicate

#19 Updated README.md (#18)
  README.md
Labels: documentation

#21 update: DEFAULT_VERSION is an obscure name, so rename it to DEFAULT_ATTACK_VERSION
  mitre_attack_csv.py
Labels: enhancement

#22 Add index.html files in csv folders/update readme.md/mitre_attack_csv
  attack-csv-data/v1.0/index.html
  attack-csv-data/v10.0/index.html
  attack-csv-data/v10.1/index.html
  attack-csv-data/v11.0/index.html
  attack-csv-data/v11.1/index.html
  attack-csv-data/v11.2/index.html
  attack-csv-data/v11.3/index.html
  attack-csv-data/v2.0/index.html
  attack-csv-data/v3.0/index.html
  attack-csv-data/v4.0/index.html
  attack-csv-data/v5.0/index.html
  attack-csv-data/v5.1/index.html
  attack-csv-data/v5.2/index.html
  attack-csv-data/v6.0/index.html
  attack-csv-data/v6.1/index.html
  attack-csv-data/v6.2/index.html
  attack-csv-data/v6.3/index.html
  attack-csv-data/v7.0/index.html
  attack-csv-data/v7.1/index.html
  attack-csv-data/v7.2/index.html
  attack-csv-data/v8.0/index.html
  attack-csv-data/v8.1/index.html
  attack-csv-data/v8.2/index.html
  attack-csv-data/v9.0/index.html
  mitre_attack_csv.py
Labels: documentation, enhancement

#25 enhance: add a script to create index.html files of CSV file links for github.io
  produce-index.sh
Labels: enhancement

#26 Add a release badge in README.md
  README.md
Labels: documentation, enhancement

#28 Added GitHub Action files
  .github/workflows/pages.yml
  .github/workflows/super_linter.yml
Labels: enhancement

#31 Fixed a GitHub style issue
  .github/workflows/pages.yml
Labels: bug
